//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by jola.rc
//
#define IDM_ABOUTBOX                    0x0010
#define IDD_ABOUTBOX                    100
#define IDS_ABOUTBOX                    101
#define IDD_JOLA_DIALOG                 102
#define IDR_MAINFRAME                   128
#define IDB_LOGO                        129
#define IDR_MENU                        131
#define IDD_DLG_CONFIG                  132
#define IDI_ORIGINAL                    135
#define IDD_DLG_ACCURACY                138
#define IDD_DLG_TOGGLE                  139
#define IDD_DLG_TYPE_TOGGLE             141
#define IDC_BN_START                    1000
#define IDC_BN_HIDE                     1000
#define IDC_LABEL                       1001
#define IDC_EDT_AREA                    1002
#define IDC_BN_CONFIG                   1002
#define IDC_SLD_SPEED                   1003
#define IDC_BN_HELP                     1003
#define IDC_EDT_LOOP                    1004
#define IDC_TXT_SPEED                   1005
#define IDC_TXT_SPEED2                  1006
#define IDC_TXT_THETA                   1006
#define IDC_TXT_TOGGLESTART             1007
#define IDC_SCRSPEED                    1008
#define IDC_CMB_STARTKEY                1009
#define IDC_CMB_ENDKEY                  1010
#define IDC_CMB_TOGGLEKEY               1011
#define IDC_SPIN_TOGGLE                 1012
#define IDC_SPIN_LOOP                   1013
#define IDC_CHK_SWITCH                  1014
#define IDC_CHK_SWITCH_AUTO             1014
#define IDC_CHK_SWITCH_TOGGLE           1015
#define IDC_RAD_KEY                     1016
#define IDC_CHK_TOGGLE_MOUSECLICK       1017
#define IDC_RAD_MOUSE                   1018
#define IDC_LBL_TOGGLEKEY               1019
#define IDC_SCRSPEED2                   1020
#define IDC_SCR_THETA                   1020
#define IDC_CMB_TYPE                    1020
#define IDC_LBL_KEY_START               1021
#define IDC_LBL_KEY_END                 1022
#define IDC_LBL_TOGGLERANGE             1023
#define IDC_LBL_TOGGLECOUNT             1024
#define IDC_CHK_F12                     1026
#define IDC_RAD_ACCURACY                1027
#define IDC_RAD_ACCURACY_NORMAL         1028
#define IDC_BN_ACCURACY                 1028
#define IDC_RAD_ACCURACY_LOW            1029
#define IDC_BN_TOGGLESTART              1029
#define IDC_VIEW_WINDOW                 32771
#define IDC_TRAY_EXIT                   32772

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        142
#define _APS_NEXT_COMMAND_VALUE         32773
#define _APS_NEXT_CONTROL_VALUE         1031
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
